# Setups geometry
/HUS/Geometry/Target/SetTargetMaterial B10
/HUS/Geometry/Target/SetBaseMaterial   C3H6O2
/HUS/Geometry/Target/SetTargetXYDim    1. cm
/HUS/Geometry/Target/SetTargetZThick   286. nm 
/HUS/Geometry/Target/SetTargetAngle    90. deg
/HUS/Geometry/Target/SetBaseXYDim      1. cm
/HUS/Geometry/Target/SetBaseZThick     36.70 nm
/HUS/Geometry/Detector/SetDet0Angle    40. deg
/HUS/Geometry/Detector/SetDet1Angle    70. deg
/HUS/Geometry/Detector/SetDet2Angle    150. deg
/HUS/Geometry/Detector/SetDet3Angle    233. deg
/HUS/Geometry/Detector/SetDet4Angle    270 deg
/HUS/Geometry/Detector/SetDet5Angle    330. deg

# Setups proton beam
#
/HUS/Beam/SetNOfParticles 1
/HUS/Beam/SetProtonEnergy 1.5 MeV

# Set file name
#
/output/FileName output.root

# Initialize kernel
#
/run/geometryModified
/run/initialize

# Run
#
/run/printProgress 10000000
/run/beamOn 200000000
