# Setups geometry
/HUS/Geometry/Target/SetTargetXYDim 1. cm
/HUS/Geometry/Target/SetTargetZThick 200. nm 
/HUS/Geometry/Target/SetTargetAngle 60. deg
/HUS/Geometry/Target/SetBaseXYDim 1. cm
/HUS/Geometry/Target/SetBaseZThick 150. nm

/HUS/Geometry/Target/SetTargetMaterial B10
/HUS/Geometry/Target/SetBaseMaterial Al

/HUS/Geometry/Detector/SetDet0Angle  40. deg
/HUS/Geometry/Detector/SetDet1Angle  70. deg
/HUS/Geometry/Detector/SetDet2Angle  150. deg
/HUS/Geometry/Detector/SetDet3Angle  233. deg
/HUS/Geometry/Detector/SetDet4Angle  270 deg
/HUS/Geometry/Detector/SetDet5Angle  330. deg

# Set file name
/output/FileName output.root

# Initialize kernel
/run/geometryModified
/run/initialize

# Run
#
/run/printProgress 10000000
/run/beamOn 200000000
